### ISSUE TITLE
efcore vector operations functions can not calculate cosine similarity

### ISSUE THREAD

**Issue by JadynWong** [pgvector/pgvector-dotnet#32]
The cosine similarity is calculated using the following sql.
```SQL
SELECT 1 - (embedding <=> '[3,1,2]') AS cosine_similarity FROM items;
```

However, an error occurs when executing a similar query using the `Pgvector.EntityFrameworkCore` vector operations functions.

```csharp
// ERROR
var scores = await ctx.Items
    .Where(x => 1 - x.Embedding!.CosineDistance(embedding) > 0.8)
    .OrderBy(x => 1 - x.Embedding!.CosineDistance(embedding))
    .Select(x => new { Entity = x, Score = 1 - x.Embedding!.CosineDistance(embedding) })
    .ToListAsync();
```

Fail log
```log
dbug: 2024/1/25 19:12:54.687 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[@__embedding_0='?' (DbType = Object)], CommandType='Text', CommandTimeout='30']
      SELECT e."Id", e.embedding, 1.0 - e.embedding <=> @__embedding_0 AS "Score"
      FROM efcore_items AS e
      WHERE 1.0 - e.embedding <=> @__embedding_0 > 0.80000000000000004
      ORDER BY 1.0 - e.embedding <=> @__embedding_0
fail: 2024/1/25 19:12:55.000 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command)
      Failed executing DbCommand (308ms) [Parameters=[@__embedding_0='?' (DbType = Object)], CommandType='Text', CommandTimeout='30']
      SELECT e."Id", e.embedding, 1.0 - e.embedding <=> @__embedding_0 AS "Score"
      FROM efcore_items AS e
      WHERE 1.0 - e.embedding <=> @__embedding_0 > 0.80000000000000004
      ORDER BY 1.0 - e.embedding <=> @__embedding_0
fail: 2024/1/25 19:12:55.190 CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query)
      An exception occurred while iterating over the results of a query for context type 'ItemContext'.
      Npgsql.PostgresException (0x80004005): 42883: operator does not exist: numeric - vector

      POSITION: 33
         at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
        Exception data:
          Severity: ERROR
          SqlState: 42883
          MessageText: operator does not exist: numeric - vector
          Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
          Position: 33
          File: parse_oper.c
          Line: 647
          Routine: op_error
```

I currently compute the cosine similarity in memory after getting the cosine distance directly.

Full console code
```csharp
// See https://aka.ms/new-console-template for more information
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;
using Pgvector;
using Pgvector.EntityFrameworkCore;

await using var ctx = new ItemContext();

ctx.Database.ExecuteSql($"DROP TABLE IF EXISTS efcore_items");
var databaseCreator = ctx.GetService<IRelationalDatabaseCreator>();
databaseCreator.CreateTables();

ctx.Items.Add(new Item { Embedding = new Vector(new float[] { 1, 1, 1 }) });
ctx.Items.Add(new Item { Embedding = new Vector(new float[] { 2, 2, 2 }) });
ctx.Items.Add(new Item { Embedding = new Vector(new float[] { 1, 1, 2 }) });
ctx.SaveChanges();

var embedding = new Vector(new float[] { 1, 1, 1 });

var items = await ctx.Database
    .SqlQuery<ItemView>($"SELECT *,1 - (embedding <=> {embedding}) as score FROM efcore_items ORDER BY 1 - (embedding <=> {embedding}) LIMIT 5")
    .ToListAsync();

// ERROR
var scores = await ctx.Items
    .Where(x => 1 - x.Embedding!.CosineDistance(embedding) > 0.8)
    .OrderBy(x => 1 - x.Embedding!.CosineDistance(embedding))
    .Select(x => new { Entity = x, Score = 1 - x.Embedding!.CosineDistance(embedding) })
    .ToListAsync();

public class ItemContext : DbContext
{
    public DbSet<Item> Items { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var connString = "Host=localhost;Database=pgvector_dotnet_test";
        optionsBuilder.UseNpgsql(connString, o => o.UseVector());
        optionsBuilder.LogTo(Console.WriteLine);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasPostgresExtension("vector");
    }
}

[Table("efcore_items")]
public class Item
{
    public int Id { get; set; }

    [Column("embedding", TypeName = "vector(3)")]
    public Vector? Embedding { get; set; }
}

public class ItemView
{
    public int Id { get; set; }

    [Column("embedding", TypeName = "vector(3)")]
    public Vector? Embedding { get; set; }

    public double score { get; set; }
}
```

**Comment by roji** [comment]
Can you please post the SQL that actually gets generated?

**Comment by JadynWong** [comment]
> Can you please post the SQL that actually gets generated?

```csharp
var query = ctx.Items
    .Where(x => 1 - x.Embedding!.CosineDistance(embedding) > 0.8)
    .OrderBy(x => 1 - x.Embedding!.CosineDistance(embedding))
    .Select(x => new { Entity = x, Score = 1 - x.Embedding!.CosineDistance(embedding) });

Console.WriteLine(query.ToQueryString());
```

Generated SQL
```sql
-- @__embedding_0='[1,1,1]' (DbType = Object)
SELECT e."Id", e.embedding, 1.0 - e.embedding <=> @__embedding_0 AS "Score"
FROM efcore_items AS e
WHERE 1.0 - e.embedding <=> @__embedding_0 > 0.80000000000000004
ORDER BY 1.0 - e.embedding <=> @__embedding_0
```

Even if I add brackets or calculate the distance in advance, it doesn't help. They generate exactly the same SQL statement.

```csharp
var query = ctx.Items
    .Where(x => (1 - (x.Embedding!.CosineDistance(embedding))) > 0.8)
    .OrderBy(x => 1 - (x.Embedding!.CosineDistance(embedding)))
    .Select(x => new { Entity = x, Score = (1 - (x.Embedding!.CosineDistance(embedding))) });

Console.WriteLine(query.ToQueryString());

query = ctx.Items
    .Select(x => new { Entity = x, Distance = x.Embedding!.CosineDistance(embedding) })
    .Where(x => 1 - x.Distance > 0.8)
    .OrderBy(x => 1 - x.Distance)
    .Select(x => new { x.Entity, Score = 1 - x.Distance });

Console.WriteLine(query.ToQueryString());
```
```SQL
-- @__embedding_0='[1,1,1]' (DbType = Object)
SELECT e."Id", e.embedding, 1.0 - e.embedding <=> @__embedding_0 AS "Score"
FROM efcore_items AS e
WHERE 1.0 - e.embedding <=> @__embedding_0 > 0.80000000000000004
ORDER BY 1.0 - e.embedding <=> @__embedding_0
-- @__embedding_0='[1,1,1]' (DbType = Object)
SELECT e."Id", e.embedding, 1.0 - e.embedding <=> @__embedding_0 AS "Score"
FROM efcore_items AS e
WHERE 1.0 - e.embedding <=> @__embedding_0 > 0.80000000000000004
ORDER BY 1.0 - e.embedding <=> @__embedding_0
```

**Comment by ankane** [comment]
@JadynWong Thanks for reporting! fwiw, you'll want to use the cosine distance in `OrderBy` to get the nearest neighbors.

@roji Thanks for the quick fix in EFCore.PG!
